### ISSUE TITLE
R link

### ISSUE THREAD

**Issue by CPernet** [CPernet/metaprivBIDS#3]
By default the rpy2 is not found (https://rpy2.github.io/) because in the package install it's not there, ie cannot import rp2

```
metaprivBIDS

Traceback (most recent call last):
  File "/users/cyrilpernet/.local/bin/metaprivBIDS", line 5, in <module>
    from metaprivBIDS.metaprivBIDS import main
  File "/indirect/staff/cyrilpernet/metaprivBIDS/metaprivBIDS/metaprivBIDS.py", line 26, in <module>
    from rpy2 import robjects
ModuleNotFoundError: No module named 'rpy2'
```

error since you changed the SUDA call

**Comment by EmiKib** [comment]
So it doesnt work after running 
conda create --name venv -c conda-forge "python>=3.7" graphviz pygraphviz r-base r-sdcMicro rpy2
?
I have also added it to the pyproject.toml file so it should work now.

**Comment by CPernet** [comment]
mmh nope it did not, but now doing conda install rpy2 separately seems to work
